/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.frostbyte.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF06677F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB6EAFF)
val onPrimaryContainerLight = Color(0xFF004E60)
val secondaryLight = Color(0xFF006A68)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9CF1EF)
val onSecondaryContainerLight = Color(0xFF00504F)
val tertiaryLight = Color(0xFF515B92)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDEE1FF)
val onTertiaryContainerLight = Color(0xFF394379)
val errorLight = Color(0xFF904A4A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFF733334)
val onErrorContainerLight = Color(0xFF7C5859)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF171C1F)
val surfaceLight = Color(0xFFABABAB)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFDBE4E8)
val onSurfaceVariantLight = Color(0xFF40484C)
val outlineLight = Color(0xFF70787C)
val outlineVariantLight = Color(0xFFBFC8CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFF88D1EB)
val surfaceDimLight = Color(0xFFDED8E0)
val surfaceBrightLight = Color(0xFFFEF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFEDE6EE)
val surfaceContainerHighestLight = Color(0xFFE7E0E8)

val primaryLightMediumContrast = Color(0xFF003C4B)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF24768E)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003D3C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF177978)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF283267)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5F69A2)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF5E2325)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFA15858)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FAFD)
val onBackgroundLightMediumContrast = Color(0xFF171C1F)
val surfaceLightMediumContrast = Color(0xFFFEF7FF)
val onSurfaceLightMediumContrast = Color(0xFF121016)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E8)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F373B)
val outlineLightMediumContrast = Color(0xFF4B5457)
val outlineVariantLightMediumContrast = Color(0xFF666E72)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF322F35)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFF7)
val inversePrimaryLightMediumContrast = Color(0xFF88D1EB)
val surfaceDimLightMediumContrast = Color(0xFFCBC4CC)
val surfaceBrightLightMediumContrast = Color(0xFFFEF7FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F1FA)
val surfaceContainerLightMediumContrast = Color(0xFFEDE6EE)
val surfaceContainerHighLightMediumContrast = Color(0xFFE1DBE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD6D0D7)

val primaryLightHighContrast = Color(0xFF00313E)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005063)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF003231)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF005251)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1D285C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3B457B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF51191C)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF763537)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FAFD)
val onBackgroundLightHighContrast = Color(0xFF171C1F)
val surfaceLightHighContrast = Color(0xFFFEF7FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE4E8)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF252D31)
val outlineVariantLightHighContrast = Color(0xFF424A4E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF322F35)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF88D1EB)
val surfaceDimLightHighContrast = Color(0xFFBDB7BE)
val surfaceBrightLightHighContrast = Color(0xFFFEF7FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5EFF7)
val surfaceContainerLightHighContrast = Color(0xFFE7E0E8)
val surfaceContainerHighLightHighContrast = Color(0xFFD9D2DA)
val surfaceContainerHighestLightHighContrast = Color(0xFFCBC4CC)

val primaryDark = Color(0xFF002B2A)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF004E60)
val onPrimaryContainerDark = Color(0xFFB6EAFF)
val secondaryDark = Color(0xFF80D5D2)
val onSecondaryDark = Color(0xFF003736)
val secondaryContainerDark = Color(0xFF00504F)
val onSecondaryContainerDark = Color(0xFF9CF1EF)
val tertiaryDark = Color(0xFFBAC3FF)
val onTertiaryDark = Color(0xFF222C61)
val tertiaryContainerDark = Color(0xFF394379)
val onTertiaryContainerDark = Color(0xFFDEE1FF)
val errorDark = Color(0xFFFFB3B2)
val onErrorDark = Color(0xFF561D20)
val errorContainerDark = Color(0xFF733334)
val onErrorContainerDark = Color(0xFFFFDAD9)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFDEE3E6)
val surfaceDark = Color(0xFF3C3B3B)
val onSurfaceDark = Color(0xFFE7E0E8)
val surfaceVariantDark = Color(0xFF40484C)
val onSurfaceVariantDark = Color(0xFFBFC8CC)
val outlineDark = Color(0xFF8A9296)
val outlineVariantDark = Color(0xFF40484C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0E8)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF06677F)
val surfaceDimDark = Color(0xFF151218)
val surfaceBrightDark = Color(0xFF3B383E)
val surfaceContainerLowestDark = Color(0xFF0F0D13)
val surfaceContainerLowDark = Color(0xFF1D1B20)
val surfaceContainerDark = Color(0xFF211F24)
val surfaceContainerHighDark = Color(0xFF2C292F)
val surfaceContainerHighestDark = Color(0xFF37343A)

val primaryDarkMediumContrast = Color(0xFFA4E6FF)
val onPrimaryDarkMediumContrast = Color(0xFF002A35)
val primaryContainerDarkMediumContrast = Color(0xFF4F9AB3)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF96EBE8)
val onSecondaryDarkMediumContrast = Color(0xFF002B2A)
val secondaryContainerDarkMediumContrast = Color(0xFF479E9C)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD6DAFF)
val onTertiaryDarkMediumContrast = Color(0xFF162155)
val tertiaryContainerDarkMediumContrast = Color(0xFF838DC8)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2D0)
val onErrorDarkMediumContrast = Color(0xFF481216)
val errorContainerDarkMediumContrast = Color(0xFFCB7A7A)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1416)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E6)
val surfaceDarkMediumContrast = Color(0xFF151218)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF40484C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD5DEE2)
val outlineDarkMediumContrast = Color(0xFFABB3B7)
val outlineVariantDarkMediumContrast = Color(0xFF899296)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E0E8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C292F)
val inversePrimaryDarkMediumContrast = Color(0xFF004F62)
val surfaceDimDarkMediumContrast = Color(0xFF151218)
val surfaceBrightDarkMediumContrast = Color(0xFF47434A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF08070B)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1F1D22)
val surfaceContainerDarkMediumContrast = Color(0xFF29272D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF343137)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF403C43)

val primaryDarkHighContrast = Color(0xFFDBF4FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF84CDE7)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D13)
val secondaryDarkHighContrast = Color(0xFFAAFFFC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF7CD1CE)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0D)
val tertiaryDarkHighContrast = Color(0xFFEFEEFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB5BFFD)
val onTertiaryContainerDarkHighContrast = Color(0xFF000631)
val errorDarkHighContrast = Color(0xFFFFECEB)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFADAC)
val onErrorContainerDarkHighContrast = Color(0xFF220002)
val backgroundDarkHighContrast = Color(0xFF0F1416)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E6)
val surfaceDarkHighContrast = Color(0xFF151218)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF40484C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE9F1F6)
val outlineVariantDarkHighContrast = Color(0xFFBBC4C8)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E0E8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004F62)
val surfaceDimDarkHighContrast = Color(0xFF151218)
val surfaceBrightDarkHighContrast = Color(0xFF524F55)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF211F24)
val surfaceContainerDarkHighContrast = Color(0xFF322F35)
val surfaceContainerHighDarkHighContrast = Color(0xFF3D3A40)
val surfaceContainerHighestDarkHighContrast = Color(0xFF49454C)







